### ISSUE TITLE
MSC level 1, 2 remaining prioritization

### ISSUE THREAD

**Issue by epicfaace** [epicfaace/CFF#112]
Level 1
- [x] Anna Daanam Sponsorship – Can we disable the dinner option in the drop down for 08/03? Instead, we can add dinner 07/30 (since camp ends 08/03, no point showing the dinner option for that day)

6. For 'Single Occupancy' – 'Adult Sharing Accommodation' should be N/A. Confirmed this with Lakshmy Ji. The intent here is, if someone does not want to share, we are not enforcing any restriction. We are basically disabling the sharing option. They will just pay $1600.00 but not share the room with anyone
What does this mean @paragbhatt ?  
@epicfaace  Nothing to do.  This is more for information that goes next to the "i" icon.  It is done.

Level 2

- [x] Wording "Bhiksha with Swamiji" should be changed to "Bhiksha with Swamin/Brahmacharin"
- [x] "i" for Yajaman level is all the way to the right – need to bring it closer to the text “Please select Yajaman level”
- [x] Gold, Silver, Bronze – description missing
- [x] confirmation email is still coming from omrun and not msc2020.(on your to-do list as well)
- [x] Yajaman description and standard description are not there yet.
- [x] There is a negative number in the drop-down showing up for age

6/29 second round of feedback:

- [x] Please remove the option for 07/30 Noon Aarti (Aarti will start only from 07/30 evening, day 1)
- [x] We'd already talked about this - annadanam sponsorship can start from 07/30 dinner, remove 08/03)
- [x] The tables now look good in the (i) section - there is a minor tweaking to be done on the 2nd line ("Sponsorship of Aarti coming 2 times, remove on the 2nd line, next to Number of guests included)
- [ ] For Standard Registration, children under 3 years of age should be free. Currently, they are being charged in the count.
- [ ] Other Sponsorship description(next to, would you be interested in sponsoring other events) - currently missing, but you'd mentioned is on your to-do list.  Just add the "i" next to it.  PB will add the content.
- [x] Very minor tweak - Jnana daanam spelling to be consistent everywhere...currently at some places, still shows Jnanam daanam

6/30 Third round of feedback:

- [ ] Give option to select Installment payment. 
           1. The delegate has a choice to pay in full or in Installment.
           2. We are giving 3 monthly installments options. All Installment payments to be completed by June 15th 2020.   Each Installment is due on the 4th of a month.  (This may be updated)
           3. When they select the payment, a question can be asked if they are paying in full or in installments. If they are paying in installments, then divide the payment into 3 monthly installments.
           4. They can do it for check, Paypal or credit card.
           5. This is true for Yajamans and Standard.  (Yajamans - NO Check!)
- [ ] Need to fix the alignment when the age of a child is entered where we need the Grade information.

**Comment by paragbhatt** [comment]
Ashwin,  I am closing this.  I have copied the incomplete ones to the new Item
'Updated MSC Issue List.'
