### ISSUE TITLE
Updated MSC Issue List.

### ISSUE THREAD

**Issue by paragbhatt** [epicfaace/CFF#116]
- [x] Give option to select Installment payment. 
           1. The delegate has a choice to pay in full or in Installment.
           2. We are giving 3 monthly installments options. Each payment is divided into three installments.   Divided it such that all payments have no fractions.  fractional part should add up to a full dollar value iin the first payment.  (too difficult?)
           3.  They can pay by Paypal or check.
           4. The first installment payment is due immediately.  If paying by paypal collect the money immediately, if paying by check,  it due in 15 days from date of registration.
           5. The second Installment is due on the 7th of a month.  This 7th has to be at least 25 days from the date of registration.  This is when the check is due, and paypal payment.
           6. The third installment is due on the 7th one month after the second payment.
           7. This is true for Yajamans and Standard.  (Yajamans - NO Paypal)
           8. All Installment payments to be fully paid by June 15th 2020.   Each Installment is due on the 7th of a month.  (This may be updated)
           9. The payment schedule should be displayed in the summary at the bottom of the form as well as in the confirmation page.
           10.  The Payment schedule should be displayed in the Confirmation Email.
- [x] We need to split Annadanam, into two.  "Add pop over next two this selection"
       When registrant selects Annadanam, two options appear, one is for **Full Day Annadanam**, and the other is for '**Per meal Annadanam**'.  "Add pop over next to the two options here"
       If the registrant selects "**Full Day Annadanam**".  He can select one of three full days 7/31, 8/1, 8/2.
       If the registrant selects "**Per Meal Annadanam**"  Then the current options for breakfast Lunch and Dinner Apper.
       "**Breakfast price is now $501**"
   Full Day Annadanam ($2501): Sponsor meals for all the delegates at the camp for a full day. This includes Bhiksha with Swami Swaroopanandaji on that day.
- [x] Add another field for both Yajaman and Standard Registration.
      **Swamins Seva:**(minimum $501) Unique opportunity to sponsor travel, accommodation and other costs of visiting Swamins and Brahmacharin. The donation will be for samashti (all Swamins).
- [x] Confirmation Email.  Add the fields of all participants, and anything that a person has opted for, then Parag will format the HTML table.  Done, Parag working on table.
- [x] We want to make sure that the person who is making the registration is at least 18 years old.  Can we add the Age with the contact name?  Then we can put a check if it is 18 or not.  And where we can copy the Contact name as first participant, we copy age too.
- [x] In the forms for the Participants information, reduce the width of Age and Gender, and Increase the width of Firstname and Last Name.
- [ ] Can we reduce the height of all the form fields, that will make it look sleeker.  Also, reduce the row height in all tables, is there an easy way? One example and Parag can do the rest.  Especially the table on top for the discounts.
- [ ] Based on Stylesheet sent by Shailaja, update the colors and fonts.  Also sent to you on slack.
- [x] For Standard Registration, children under 3 years of age should be free. Currently, they are being charged in the count.
- [x] Add a title for the contact name called "Contact Person", just above the contact name.  Rename contact firstname to 'First Name, contact last name to just "Last Name" and same with middle.
- [x] Need to fix the alignment when the age of a child is entered where we need the Grade information. Ok if this line is split in two lines.  Move Allergies and Special to next line and rename them as "Allergies/Dietary Selection" and "Special needs if any?" 
 Age and Gender boxes can be smaller.  Best if we can make age an integer so, we accept just numbers and no up/down arrows.
 - [x] Sponsor Mahasamadhi Day Puja option for  Gold and Silver Yajamans - Can we default it to 'Yes'? Grey it out for Gold and Silver by selecting "yes
 - [x] For Yajamans, the text for Aarti sponsorship should say One,Two or three Aartis (or whatever number is applicable as per the sponsorship level).
- [x] Yajaman Selection - Description should clearly specify the "Included" delegates.  For this, below the "Number of People"  please specify '4 people are included' for gold, '2 people are included' for silver and '1 person is included' as part of bronze
- [x] Add new text box, one per order just before Accept Terms  call it Additional requests.  Add an 'i' next to it with " Do you have any other requests?  example, Room with one king bed or two queen beds, or any other request?  While we cannot guarantee, the MSC2020 team will try to accomadate your requests".

**Comment by epicfaace** [comment]
What does "Yajmans - NO Check!" mean?

**Comment by paragbhatt** [comment]
I meant Yajamans no PayPal. 
Also these are instructions for you.  Not to display it as is. 
Regards,
Parag
====
