### ISSUE TITLE
[MSC] Paypal with installment gives an error

### ISSUE THREAD

**Issue by epicfaace** [epicfaace/CFF#137]
Reported by @paragbhatt on slack (please make a github issue in the future)

![image](https://user-images.githubusercontent.com/1689183/61735450-d97afa80-ad38-11e9-8eec-910bd82c1f7a.png)

Steps:
1. Go to https://forms.chinmayamission.com/v2/forms/5c96811ed0443d00011255d5?responseId=5d363e420d053400019031d5
2. Click "Submit" and then "pay now"
3. Click on "Paypal check out" to sign in to subscribe.
4. You will see the error screen.

**Comment by epicfaace** [comment]
The issue was that formOptions had:

```
  "paymentMethods": {
    "paypal_classic": {
      "zip": "$address.zip",
```

Changed the above to 

```
  "paymentMethods": {
    "paypal_classic": {
      "zip": "$address.zipcode",
```

Because there is no field called `zip`, only a field called `zipcode`. Thus, previously it was setting zip to "."

Should we look into not making "." the default value for undefined fields, or maybe instead, just having validation on paypal fields _before_ it's sent to PayPal?

**Comment by paragbhatt** [comment]
Will it work for international PayPal payees?

**Comment by epicfaace** [comment]
Not sure, it probably should as long as they pay in USD.
