### ISSUE TITLE
Registrations Summary

### ISSUE THREAD

**Issue by paragbhatt** [epicfaace/CFF#186]
We need the following in the Registrations summary.

- [x] Option to see the center the delegate goes to.  (This will be similar to Training)
- [x] Total number of rooms currently needed
- [x] Total number of children by grade (along with the data dump)
- [x] Total number of Sethukaris (along with the data dump)
- [x] Total number of Yajaman families (by category)
- [x] Collections of money -- received and yet to be received. For the yet to be received, a way to indicate if the payment is past due and we need to follow up.
- [ ] Single room accommodation requested and a dump of the delegates in this category
- [ ] Double room accommodation requested and a dump of the delegates in this category -- with a way of showing how many more delegates can be assigned to this room
- [ ] Triple room accommodation requested and a dump of the delegates in this category -- with a way of showing how many more delegates can be assigned to this room
- [ ] Quad room accommodation requested and a dump of the delegates in this category -- with a way of showing how many more delegates can be assigned to this room.
- [ ] Add a 'Category' column at the Participants level to show 'Adult, Sethukari, CHYK, Bala Vihar' options

**Comment by epicfaace** [comment]
How do we know if someone is a Sethukari? An age range?

**Comment by paragbhatt** [comment]
CHYK is 18 - 28
Setukari is 29-40

Use this age.  I will get confirmation.
